// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDquMPffuKu4nahyefFJTpyGLXztpo0Bfo',
    appId: '1:630782007797:web:293cc8edd3f6dd832168bc',
    messagingSenderId: '630782007797',
    projectId: 'threadly-e5fb2',
    authDomain: 'threadly-e5fb2.firebaseapp.com',
    storageBucket: 'threadly-e5fb2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrwVS8fX3cgCRgm-JIsaVIFgrfd6lVrRE',
    appId: '1:630782007797:android:2f6fbd44a7705e322168bc',
    messagingSenderId: '630782007797',
    projectId: 'threadly-e5fb2',
    storageBucket: 'threadly-e5fb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAixaGgFlk5LjlQ0dt0yyAQ4-x-s2_b0TQ',
    appId: '1:630782007797:ios:dcaf39fbf74e1e882168bc',
    messagingSenderId: '630782007797',
    projectId: 'threadly-e5fb2',
    storageBucket: 'threadly-e5fb2.firebasestorage.app',
    iosBundleId: 'com.example.threadly',
  );
}
